# Generated by Django 6.1.1 on 2026-10-05 05:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ciudadanos', '0002_alter_vecino_direccion_alter_vecino_nombre_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidenteSeguridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eliminado', models.DateTimeField(blank=True, null=True, verbose_name='eliminado')),
                ('fecha_deteccion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha de detección')),
                ('descripcion', models.TextField(verbose_name='descripción')),
                ('datos_afectados', models.TextField(blank=True, verbose_name='datos afectados')),
                ('gravedad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=10, verbose_name='gravedad')),
                ('notificado_apdp', models.BooleanField(default=False, verbose_name='notificado a la APDP')),
                ('fecha_notificacion_apdp', models.DateField(blank=True, null=True, verbose_name='fecha de notificación a la APDP')),
                ('notificado_titulares', models.BooleanField(default=False, verbose_name='notificado a los titulares')),
            ],
            options={
                'verbose_name': 'incidente de seguridad',
                'verbose_name_plural': 'incidentes de seguridad',
                'ordering': ['-fecha_deteccion'],
            },
        ),
        migrations.CreateModel(
            name='ActividadTratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eliminado', models.DateTimeField(blank=True, null=True, verbose_name='eliminado')),
                ('nombre', models.CharField(max_length=120, verbose_name='nombre')),
                ('finalidad', models.CharField(max_length=200, verbose_name='finalidad')),
                ('base_licitud', models.CharField(choices=[('deber_legal', 'Cumplimiento de un deber legal'), ('funcion_publica', 'Ejercicio de funciones públicas'), ('interes_vital', 'Interés vital del titular'), ('consentimiento', 'Consentimiento del titular')], default='deber_legal', max_length=20, verbose_name='base de licitud')),
                ('categorias_datos', models.CharField(max_length=200, verbose_name='categorías de datos')),
                ('destinatarios', models.CharField(blank=True, max_length=200, verbose_name='destinatarios')),
                ('plazo_conservacion_dias', models.PositiveIntegerField(blank=True, null=True, verbose_name='plazo de conservación (días)')),
                ('medidas_seguridad', models.CharField(blank=True, max_length=200, verbose_name='medidas de seguridad')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actividades_tratamiento', to=settings.AUTH_USER_MODEL, verbose_name='responsable')),
            ],
            options={
                'verbose_name': 'actividad de tratamiento',
                'verbose_name_plural': 'actividades de tratamiento',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Consentimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eliminado', models.DateTimeField(blank=True, null=True, verbose_name='eliminado')),
                ('otorgado', models.BooleanField(default=True, verbose_name='otorgado')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha')),
                ('version_politica', models.CharField(blank=True, max_length=40, verbose_name='versión de la política')),
                ('revocado', models.BooleanField(default=False, verbose_name='revocado')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consentimientos', to='cumplimiento.actividadtratamiento', verbose_name='actividad')),
                ('vecino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consentimientos', to='ciudadanos.vecino', verbose_name='titular')),
            ],
            options={
                'verbose_name': 'consentimiento',
                'verbose_name_plural': 'consentimientos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('crear', 'Crear'), ('editar', 'Editar'), ('eliminar', 'Eliminar'), ('ver', 'Ver'), ('exportar', 'Exportar')], max_length=10, verbose_name='acción')),
                ('tabla', models.CharField(blank=True, max_length=80, verbose_name='tabla')),
                ('objeto_id', models.CharField(blank=True, max_length=40, verbose_name='objeto')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('detalle', models.CharField(blank=True, max_length=200, verbose_name='detalle')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditoria', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'registro de auditoría',
                'verbose_name_plural': 'registros de auditoría',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudTitular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eliminado', models.DateTimeField(blank=True, null=True, verbose_name='eliminado')),
                ('tipo', models.CharField(choices=[('acceso', 'Acceso'), ('rectificacion', 'Rectificación'), ('supresion', 'Supresión'), ('oposicion', 'Oposición'), ('portabilidad', 'Portabilidad'), ('bloqueo', 'Bloqueo temporal')], max_length=20, verbose_name='tipo')),
                ('estado', models.CharField(choices=[('ingresada', 'Ingresada'), ('en_proceso', 'En proceso'), ('respondida', 'Respondida'), ('rechazada', 'Rechazada')], default='ingresada', max_length=20, verbose_name='estado')),
                ('fecha_solicitud', models.DateField(default=django.utils.timezone.localdate, verbose_name='fecha de solicitud')),
                ('fecha_limite', models.DateField(blank=True, null=True, verbose_name='fecha límite')),
                ('fecha_respuesta', models.DateField(blank=True, null=True, verbose_name='fecha de respuesta')),
                ('detalle', models.TextField(blank=True, verbose_name='detalle')),
                ('respondido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_respondidas', to=settings.AUTH_USER_MODEL, verbose_name='respondido por')),
                ('vecino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='ciudadanos.vecino', verbose_name='titular')),
            ],
            options={
                'verbose_name': 'solicitud del titular',
                'verbose_name_plural': 'solicitudes del titular',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
