# Generated by Django 6.1.1 on 2026-09-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delegacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eliminado', models.DateTimeField(blank=True, null=True, verbose_name='eliminado')),
                ('codigo', models.CharField(max_length=40, unique=True, verbose_name='código')),
                ('nombre', models.CharField(max_length=120, verbose_name='nombre')),
                ('direccion', models.CharField(blank=True, max_length=200, verbose_name='dirección')),
                ('comuna', models.CharField(blank=True, max_length=80, verbose_name='comuna')),
            ],
            options={
                'verbose_name': 'delegación',
                'verbose_name_plural': 'delegaciones',
                'ordering': ['nombre'],
            },
        ),
    ]
