# Generated by Django 6.1.1 on 2026-10-05 05:54

import apps.common.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='delegacion',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delegaciones_responsable', to=settings.AUTH_USER_MODEL, verbose_name='responsable'),
        ),
        migrations.AlterField(
            model_name='delegacion',
            name='codigo',
            field=models.CharField(max_length=40, unique=True, validators=[apps.common.validators.validar_codigo], verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='delegacion',
            name='comuna',
            field=models.CharField(blank=True, max_length=80, validators=[apps.common.validators.validar_comuna], verbose_name='comuna'),
        ),
        migrations.AlterField(
            model_name='delegacion',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, validators=[apps.common.validators.validar_direccion], verbose_name='dirección'),
        ),
        migrations.AlterField(
            model_name='delegacion',
            name='nombre',
            field=models.CharField(max_length=120, validators=[apps.common.validators.validar_nombre], verbose_name='nombre'),
        ),
    ]
