# Generated by Django 6.1.1 on 2026-10-05 05:54

import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='codigo',
            field=models.SlugField(blank=True, max_length=40, null=True, unique=True, validators=[apps.common.validators.validar_codigo], verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, validators=[apps.common.validators.validar_catalogo], verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='nombre',
            field=models.CharField(max_length=60, unique=True, validators=[apps.common.validators.validar_nombre], verbose_name='nombre'),
        ),
    ]
