# Generated by Django 6.1.1 on 2026-09-26 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vecino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='nombre')),
                ('rut', models.CharField(max_length=15, unique=True, verbose_name='RUT')),
                ('direccion', models.CharField(blank=True, max_length=200, verbose_name='dirección')),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='teléfono')),
                ('tipo_gestion', models.CharField(blank=True, max_length=80, verbose_name='tipo de gestión')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10, verbose_name='estado')),
                ('territorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vecinos', to='organizacion.delegacion', verbose_name='territorio')),
            ],
            options={
                'verbose_name': 'vecino',
                'verbose_name_plural': 'vecinos',
                'ordering': ['nombre'],
            },
        ),
    ]
