# Generated by Django 6.1.1 on 2026-10-05 05:54

import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudadanos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vecino',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, validators=[apps.common.validators.validar_direccion], verbose_name='dirección'),
        ),
        migrations.AlterField(
            model_name='vecino',
            name='nombre',
            field=models.CharField(max_length=120, validators=[apps.common.validators.validar_nombre], verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='vecino',
            name='rut',
            field=models.CharField(max_length=15, unique=True, validators=[apps.common.validators.validar_rut], verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='vecino',
            name='telefono',
            field=models.CharField(blank=True, max_length=30, validators=[apps.common.validators.validar_telefono], verbose_name='teléfono'),
        ),
        migrations.AlterField(
            model_name='vecino',
            name='tipo_gestion',
            field=models.CharField(blank=True, max_length=80, validators=[apps.common.validators.validar_catalogo], verbose_name='tipo de gestión'),
        ),
    ]
