# Generated by Django 6.1.1 on 2026-09-28 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eliminado', models.DateTimeField(blank=True, null=True, verbose_name='eliminado')),
                ('nombre', models.CharField(max_length=120, verbose_name='nombre')),
                ('descripcion', models.CharField(blank=True, max_length=200, verbose_name='descripción')),
            ],
            options={
                'verbose_name': 'tipo de atención',
                'verbose_name_plural': 'tipos de atención',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eliminado', models.DateTimeField(blank=True, null=True, verbose_name='eliminado')),
                ('nombre', models.CharField(max_length=120, verbose_name='nombre')),
                ('descripcion', models.CharField(blank=True, max_length=200, verbose_name='descripción')),
                ('delegacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='metas', to='organizacion.delegacion', verbose_name='delegación')),
            ],
            options={
                'verbose_name': 'meta',
                'verbose_name_plural': 'metas',
                'ordering': ['delegacion', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='SubAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eliminado', models.DateTimeField(blank=True, null=True, verbose_name='eliminado')),
                ('nombre', models.CharField(max_length=120, verbose_name='nombre')),
                ('tipo_atencion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sub_atenciones', to='catalogos.tipoatencion', verbose_name='tipo de atención')),
            ],
            options={
                'verbose_name': 'sub atención',
                'verbose_name_plural': 'sub atenciones',
                'ordering': ['tipo_atencion', 'nombre'],
            },
        ),
    ]
