# Generated by Django 6.1.1 on 2026-10-05 05:54

import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meta',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, validators=[apps.common.validators.validar_catalogo], verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='meta',
            name='nombre',
            field=models.CharField(max_length=120, validators=[apps.common.validators.validar_nombre], verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='subatencion',
            name='nombre',
            field=models.CharField(max_length=120, validators=[apps.common.validators.validar_nombre], verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='tipoatencion',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, validators=[apps.common.validators.validar_catalogo], verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='tipoatencion',
            name='nombre',
            field=models.CharField(max_length=120, validators=[apps.common.validators.validar_nombre], verbose_name='nombre'),
        ),
    ]
