# Generated by Django 6.1.1 on 2026-10-05 05:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0002_alter_meta_descripcion_alter_meta_nombre_and_more'),
        ('ciudadanos', '0002_alter_vecino_direccion_alter_vecino_nombre_and_more'),
        ('organizacion', '0002_delegacion_responsable_alter_delegacion_codigo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eliminado', models.DateTimeField(blank=True, null=True, verbose_name='eliminado')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha')),
                ('motivo', models.CharField(max_length=200, verbose_name='motivo')),
                ('detalle', models.TextField(blank=True, verbose_name='detalle')),
                ('estado', models.CharField(choices=[('ingresada', 'Ingresada'), ('en_proceso', 'En proceso'), ('cerrada', 'Cerrada'), ('derivada', 'Derivada')], default='ingresada', max_length=20, verbose_name='estado')),
                ('canal', models.CharField(blank=True, choices=[('presencial', 'Presencial'), ('telefono', 'Teléfono'), ('web', 'Web')], max_length=20, verbose_name='canal')),
                ('delegacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atenciones', to='organizacion.delegacion', verbose_name='delegación')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atenciones', to=settings.AUTH_USER_MODEL, verbose_name='funcionario')),
                ('sub_atencion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atenciones', to='catalogos.subatencion', verbose_name='sub atención')),
                ('tipo_atencion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atenciones', to='catalogos.tipoatencion', verbose_name='tipo de atención')),
                ('vecino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atenciones', to='ciudadanos.vecino', verbose_name='vecino')),
            ],
            options={
                'verbose_name': 'atención',
                'verbose_name_plural': 'atenciones',
                'ordering': ['-fecha'],
            },
        ),
    ]
